---
  - hosts: all
    roles:
      - { role: slave, when: "is_slave == 'true'" }

    pre_tasks:
      - name: Update APT's cache
        apt: update_cache=yes

      - name: Install python-software-properties and software-properties-common and GIT
        apt: pkg={{item}} state=latest
        with_items:
          - software-properties-common
          - python-software-properties
          - git

  - include: services/system/system.yml
  - include: services/nginx/nginx.yml
  - include: services/varnish/varnish.yml
  - include: services/mariadb/mariadb.yml
  - include: services/php7-fpm/php7-fpm.yml
  - include: services/memcached/memcached.yml
  - include: wordpress/wordpress.yml
