---
  - name: write /etc/default/varnish
    action: template src=templates/varnish dest=/etc/default/varnish
    notify:
      - restart varnish

  - name: write /etc/varnish/default.vcl
    action: template src=templates/default.vcl dest=/etc/varnish/default.vcl
    notify:
      - restart varnish

  - name: Make sure sur varnish.service.d exists
    file: path=/etc/systemd/system/varnish.service.d state=directory

  - name: write /etc/systemd/system/varnish.service.d/customexec.conf
    action: template src=templates/customexec.conf dest=/etc/systemd/system/varnish.service.d/customexec.conf
    notify:
      - restart varnish

  - name: Reload systemd daemons
    command: systemctl daemon-reload
    notify:
      - restart varnish

  - name: Run varnish upon startup
    command: systemctl enable varnish
    notify:
      - restart varnish

  - name: Restart VARNISH
    service:
        name: 'varnish'
        state: 'restarted'
