---

  - name: Add nginx key
    apt_key: url=http://nginx.org/keys/nginx_signing.key

  - name: Add nginx repository
    apt_repository: repo='deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx'

  - name: install nginx
    action: apt name=nginx

  - name: ensure sites-available/ directory exists
    file: path=/etc/nginx/sites-available mode=0755 state=directory

  - name: ensure sites-enabled/ directory exists
    file: path=/etc/nginx/sites-enabled mode=0755 state=directory

  - name: Ensure the web directory exists
    file: path=/var/www owner=www-data group=www-data state=directory

  - name: Remove the default nginx vhost
    file: path=/etc/nginx/sites-enabled/default state=absent

  - name: write nginx.conf
    action: template src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify:
      - restart nginx
