---

  - name: install ansible
    action: apt name=ansible

  - name: Create /slave folder
    file: path=/slave state=directory

  - name: Git clone ansible sync project
    git: repo=https://github.com/Piwee-DEV/ansible-piwee-synchronize-with-master-node.git dest=/slave/sync

  - name: Create the ansible-inventory file
    action: template src=templates/ansible-inventory.j2 dest=/slave/sync/ansible-inventory

  - name: Setup master sync cron task
    cron: name="Sync with master" hour="4" minute="30" job="ansible-playbook /slave/sync/playbook.yml -i /slave/sync/ansible-inventory  --user=root"

  - name: Generate SSH public key
    user: name=root generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa

  - name: Install SSHPASS to ssh a host and specify password inline in order to inject our public key
    action: apt name=sshpass

  - name: ssh-copy-id with the master server
    shell: sshpass -p {{ master_ssh_password }} ssh-copy-id -o StrictHostKeyChecking=no root@{{ master_ip }}

  - name: ssh-copy-id with the local server
    shell: sshpass -p {{ slave_ssh_password }} ssh-copy-id -o StrictHostKeyChecking=no root@127.0.0.1
